import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app", //This is the description of the website shown in the search engine results page
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}

//EXPLANATION
/*
* Explain className={`${inter.className} antialiased` 
* This is a CSS class that applies the Inter font and antialiasing to the entire app.
* The inter.className is the name of the font family.
* The antialiased class is a CSS class that applies antialiasing to the text.
*   antialiased is a CSS class that applies antialiasing to the text and antialiasing is a CSS property that makes the text look sharper and more readable.
*/